on:
  workflow_dispatch:
  push:
    branches: [master, index]
name: Quarto Publish
jobs:
  retrieve:
    runs-on: ubuntu-latest
    container:
      image: lennartwittkuhn/datalad:0.17.6
    steps:
      - name: Install and Build
        run: |
          datalad install --get-data https://github.com/$GITHUB_REPOSITORY
          datalad unlock -d replay-illustrations replay-illustrations/illustrations
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: illustrations
          path: replay-illustrations/illustrations
  build-deploy:
    runs-on: ubuntu-latest
    needs: retrieve
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: illustrations
          path: replay-illustrations/illustrations
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'
      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1
      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}